ARG BUILD_FROM
FROM ghcr.io/fastybird/smart-panel:0.5.0-alpha

LABEL \
    io.hass.name="Smart Panel" \
    io.hass.description="A customizable display interface for visualizing and controlling smart homes" \
    io.hass.type="addon" \
    io.hass.version="0.5.0-alpha"
